### ISSUE TITLE
Support Bayesian Convolutional Neural Networks

### ISSUE THREAD

**Issue by ltiao** [data61/aboleth#74]
Add a Variational Convolutional layer

**Comment by nbro** [comment]
@dsteinberg The variational convolutional layer can be found at https://aboleth.readthedocs.io/en/latest/api/layers.html#aboleth.layers.Conv2DVariational, but where can I find the demo that shows the usage of a variational or Bayesian CNN?

**Comment by dsteinberg** [comment]
Hi @nbro, we have a non-variational demo here:
https://github.com/gradientinstitute/aboleth/blob/master/demos/mnist_softmax_regression.py
It should be reasonably strait-forward to convert it to a Bayesian version by replacing the `Dense` layers with `DenseVariational` layers, and the `max_posterior` loss with an `elbo` loss (as per the example in the README: https://github.com/gradientinstitute/aboleth#why

I hope this helps!
